[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install -g pnpm@9", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd server && pnpm build"]

[start]
cmd = "cd server && node dist/main.js"
