[build]
command = "npm install -g pnpm && pnpm install && cd server && pnpm build"

[deploy]
command = "cd server && node dist/main.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
